language: node_js
node_js: stable
services:
- postgresql
addons:
  postgresql: '10'
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10
deploy:
  provider: heroku
  api_key:
    secure: jafKq8EDM+4ewkvVG/VWSbE7RkOObkoDB7taHwsrr2X9huGFE2nNZ2eCSsqr7yD55AcwKsoBoK1BYLtQ3tFU04s3E8QFgvgyOsv+U3dLb6uFO0bq5PHvJ7vDN1O8O5J52xxK3yOZRcIJ/ReRH2nrndVBaDntrC1BOvAnGmBcmq50rkDXafp6XMfYaM01wD0JszNBzm/HpBaRTGAty8Z3XN4bgc+MMEdkX/0ONO4Fr97oHc1YaLlhdSvp7NP9hNQ57q9LxPPfb/QKwj2kcP8YPRS0T1df4fIkXLqEraKnJTI05DLDHt54U+b0s4Vlrhh4WB9YWHZ2mGzWsVDkeleFG5pG0ZzAlq5poEVD3ciFDML9rsvbRZMXRHGGRQ78vPVxJAzU1SIFMeesK/5TeNJDHb867wDbczRjMV034ZFZHeY6LZqrstGzLwcCbQOphd9Ugf2CnmBZfrrHy89iPpa/p0Cd/8fEXmFWFc9upOw7u64+4xzHnQWIrn2C+2KZRo3Li+SUkvCLrUqT+60fl1Pv+/o4g4YZZuz/aABdPk8u7Og78JG5O/rB0DdKBl6eT+vlJzoYEwWChtRWDE8fvdt6cJ0YDZYyRmtHIPNxMYWLPvdGF3G/QVNtwok0p8Ufye2ejiU1FcFvje5WCxIS3OV7y6ItMdZ8rrL5tUf+VAKQekM=
  app: mockshop-staging
  on:
    repo: chubbystrings/mock-shop
  skip_cleanup: true
install:
- npm install
script:
- npm test
env:
  global:
    secure: kN2Tv1Q7SLIfk16pNkd8r+JWQx78vC+KWVlp4uZHBOwtTXZPiJ80G9I6Wb+fmK4atzl3C584+o3i1o/1qRQ6A3n+FZDaLTYZi1FyPZjCBxyVZqXH5gUJCZ78MNItUWR6eji9JofrVVnhoe1UDXyq5NNVrlgVOXU/WDoRi6bMLnjzYo8i+JE4y0m9jQhzYq0Ou0RM7qdPASxmlm6FkCKzmdFaLjW7l8kL8oDtIwl6CI6KY9TL80pP974YpSfiGOAC6ZNff5/vV0Gffpfbygnj0Z3iovrjDH2kTONJjZbQlDm1lVYjKuZJ9P+FwaAFTDQh5rZ64XWwjvXQP2oKVWg2WvG3d/Ag7OTpfA5vuSq8EP9BeShj4UNAF0SHM7cXYdckr83xKwbyKTN1AhNOIB5jSM2EjL/xtbKH5IlZRghf08cq+5Lr4LMG7sB8/NZ/KLzWcAhc4cHU/koa4RPuhAuoTNKgDP1maMjTgId+jCjuLr2HjTivgo645YhVEa42gy75Hx+cnNNs/M4xN85dKlBntcm+wEb8Jx3vTAh1nuDAMF5gnYPicAe+9D7qYAhCKXgfLuO+mZELlH7fD0nCmH+Y+7JLvXrjTXLfwwsoGahKAY0Ya3r+4gb/cTqlLVaxg3D8+r6tvVzqc/HX3Z1+HewsDb2KKPVPbpSkKN3uul1Q90c=
